version: 0.0
os: linux
files:
  - source: /
    destination: C:\Users\Administrator\mod_photograph_node
hooks:
  BeforeInstall:
    - location: scripts\before_install.ps1
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts\after_install.ps1
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts\application_start.ps1
      timeout: 300
      runas: root
